apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  labels:
    app: testapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
       app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: php-redis2
        image: gcr.io/google_samples/gb-frontend:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
