apiVersion: v1
kind: Service
metadata:
  name: postgres-app
spec:
  selector:
    app: postgres
  ports:
    port: 5432
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:9.6.2"
          env:
            - name: POSTGRES_USER
              valuefrom:
                configMapKeyRef:
                  name: mealplan-config
                  key: postgres_user
            - name: POSTGRESS_PASSWORD
                valuefrom:
                configMapKeyRef:
                  name: mealplan-config
                  key: postgres_password
          ports:
            - containerPort: 5432
              name: postgres
