apiVersion: v1
kind: Pod
metadata:
  name: claimpod
spec:
  containers:
  - name: my-claim-container
    image: nginx
    volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: mypvc
