apiVersion: v1
kind: Pod
metadata:
  name: forlinveliness-html
  labels:
    check: liveliness
spec:
  containers:
  - name: forlinveliness-html-cnt
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3

