apiVersion: v1
kind: Pod
metadata:
  name: forliveliness
  labels:
    check: liveliness
spec:
  containers:
  - name: forliveliness-cnt
    image: k8s.gcr.io/busybox
    args:
    - /bin/bash
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

