apiVersion: v1
kind: Pod
metadata:
  name: podwithprojectedvolume
  namespace: all
spec:
  containers:
  - name: podwithprojectedvolume-cnt
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass
