kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcfodpod
  #  namespace: forpvandpvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
