apiVersion: v1
kind: Pod
metadata:
  name: forqos
  namespace: qos-example
spec:
  containers:
  - name: forqos-cnt
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "100m"
      requests:
        memory: "200Mi"
        cpu: "100m"

