apiVersion: v1
kind: Pod
metadata:
  name: volumeforpod
  namespace: forvolume
spec:
  containers:
  - name: volumeforpod-cnt
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}

