apiVersion: v1
kind: Pod
metadata:
  name: pod-testing
  labels:
    app: myapp
spec:
  containers:
  - name: pod-test-container
    image: busybox
    command: ['ls']
#    command: ['/home/touch abc.txt']
    command: ['ls /home']

