apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edu-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: edu-deployment-app
        image: jenkins
        ports:
        - containerPort: 8080   
