apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-10-25T04:14:16Z
  name: nginx-pod
  namespace: default
  resourceVersion: "46585"
  selfLink: /api/v1/namespaces/default/pods/nginx-pod
  uid: 70311cf4-d80c-11e8-83ab-0a4ce1c3ba98
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-22nrb
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: saineel145.mylabserver.com
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-22nrb
    secret:
      defaultMode: 420
      secretName: default-token-22nrb
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-10-25T04:14:16Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-10-26T01:42:42Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-10-26T01:42:42Z
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-10-25T04:14:16Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://761f8b0d7f3b653bd94da2270e3149358fc9dcd2682aeb51746591239eeab974
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:b73f527d86e3461fd652f62cf47e7b375196063bbbd503e853af5be16597cb2e
    lastState:
      terminated:
        containerID: docker://14c676cedf9cf57c894ddd6c64ac8929fde2be60927e197025b003f9cdbfdd67
        exitCode: 0
        finishedAt: 2018-10-25T20:08:38Z
        reason: Completed
        startedAt: 2018-10-25T17:59:54Z
    name: nginx
    ready: true
    restartCount: 3
    state:
      running:
        startedAt: 2018-10-26T01:42:41Z
  hostIP: 172.31.111.176
  phase: Running
  podIP: 10.244.1.11
  qosClass: BestEffort
  startTime: 2018-10-25T04:14:16Z
