apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    zone: production
    version: v1
spec:
  containers:
  - name: sample
    image: devopstrainer/ubuntu:sample
    ports:
    - containerPort: 8080


