apiVersion: v1
kind: pod
metadata:
  name: config-test-pod
spec:
  containers:
    - name: test
      image: busybox
      command: [ "/bin/sh","-c", "env" ]
      env:
        - name: city_name
          valueFrom:
	    configMapKeyRef:
              name: my-map
              key: city
  restartPolicy: Never
