apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: myapp
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: myapp
---
#the next code is for statefulstate

apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: nginx-service-statefulset
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: "nginx-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1G
