apiVersion: v1
kind: Pod
metadata:
  name: specifyinginitcontainer
  labels:
    app: myapp
spec:
  containers:
  - name: myappcontainer
    image: busybox
    command: ['sh', '-c', 'echo this is my app && sleep 2600']
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
  - name: init-mydb
    image: busybox
    command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']
