apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1234
  - name: https
    port: 443
    protocol: TCP
    targetPort: 4321
---

#for loadbalancer

apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app: myapp
  ports:
  - name: https
    port: 80
    protocol: TCP
    targetPort: 2345
  clusterIP: 10.0.171.239
  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
 
---



