apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storaage: 5Gi
  volumeMode: Filesystem
  accessModes: ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
   path: /tmp
   server: 172.17.0.2
