apiVersion: apps/v1
kind: Deployment
metadata:
  name: nameinfirstmetadata
spec:
  replicas: 4
  selector:
    matchLabels:
      aaa: bbb
  template:
    metadata:
      name: nameinsecondmetadata
      labels:
        aaa: bbb
    spec:
      containers:
      - image: linuxacademycontent/kubeserve:v1
        name: nameincontainer


