apiVersion: v1
kind: Pod
metadata:
  name: resource1
spec:
  nodeSelector:
    kubernetes.io/hostname: "saineel142c.mylabserver.com"
  containers:
  - image: busybox
    name: 1resource
    command:
    - "sleep"
    - "3600"
    resources:
      requests:
        cpu: 20m
        memory: 20Mi

