apiVersion: v1
kind: Pod
metadata:
  name: resource2
spec:
  nodeSelector:
    kubernetes.io/hostname: "saineel142c.mylabserver.com"
  containers:
  - name: resource2
    image: busybox
    command:
    - "sleep"
    - "3600"
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
