apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: test-daemon
spec:
  selector:
    matchLabels:
      apps: ssd-monitor
  template:
    metadata:
      labels:
        apps: ssd-monitor
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: daemonmain
        image: linuxacademycontent/ssd-monitor
