apiVersion: v1
kind: Pod
metadata:
   name: pod-for-secret
spec:
  containers:
  - name: podforsecrete
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
