apiVersion: v1
kind: Pod
metadata:
  name: frontend2
spec:
  containers:
  - name: db2
    image: mysql
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
  - name: wp2
    image: wordpress
    resources:
      requests:
         ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"

